services:
  db:
    image: postgres
    container_name: dance_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=dance_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d

  app:
    build: 
      context: ./backend
      dockerfile: ./deploy.Dockerfile
    container_name: dance_app
    depends_on:
      - db
    command: npm run deploy
    environment:
     - DB_USER=${DB_USER}
     - DB_PASSWORD=${DB_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: ./deploy.Dockerfile
      args:
        VITE_APP_URL: http://localhost:${PORT_APP}
    container_name: dance_frontend
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    container_name: dance_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:8080
    depends_on:
      - app
      - frontend

volumes:
  db_data:
